### ISSUE TITLE
this csd source makes noise and low sound quality severely.

### ISSUE THREAD

**Issue by audiorecorder** [hlolli/csound-wasm#1]
I have tested with csound-wasm-browser.js
but not works well. Noise and low quality of the sound.

https://raw.githubusercontent.com/csound/examples/master/csd/xanadu-high-resolution.csd

**Comment by hlolli** [comment]
The problem here is simple, this piece isn't written for 0dbfs = 1, so you have to give a high 0dbfs value for it not to clip, here's an example https://jsfiddle.net/8agv320r/

**Comment by audiorecorder** [comment]
Thanks. It works.
It would be better to automatically recognize the zerodbfs value when playing.

**Comment by hlolli** [comment]
I've considered it, but it's tricky to analyze it, as the value can be set in CsOptions and 0dbfs opcode, the lack of 0dbfs can not be accurately estimated as it's hard to know if the author of a csd uses cli flags to set the 0dbfs value. On the positive side, for the last 10-18 years, almost all csd's use 0dbfs = 1, so it's really an exception (or old files) that are running on different values.
